# Generated by Django 3.2.22 on 2023-10-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=35)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dept_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=35)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='labsubject_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=35)),
                ('syllabus', models.TextField()),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.course_table')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=35)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('programming_lang', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.course_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=35)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.dept_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='system_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.IntegerField()),
                ('details', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='system_stud_allo_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.student_table')),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.system_table')),
            ],
        ),
        migrations.CreateModel(
            name='sub_staff_allo_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.staff_table')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.labsubject_table')),
            ],
        ),
        migrations.CreateModel(
            name='student_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.staff_table')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.student_table')),
            ],
        ),
        migrations.CreateModel(
            name='staff_lab_allocatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=30)),
                ('SUBJECT_STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.sub_staff_allo_table')),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.FileField(upload_to='')),
                ('camera_image', models.FileField(upload_to='')),
                ('timedate', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.system_table')),
            ],
        ),
        migrations.CreateModel(
            name='lab_assistant_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=35)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='exam_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('details', models.CharField(max_length=150)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.staff_table')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.labsubject_table')),
            ],
        ),
        migrations.CreateModel(
            name='doubt_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.TextField()),
                ('date', models.DateField()),
                ('reply', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.staff_table')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.student_table')),
            ],
        ),
        migrations.AddField(
            model_name='course_table',
            name='DEPARTMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.dept_table'),
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('date', models.DateField()),
                ('reply', models.TextField()),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.staff_table')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.student_table')),
            ],
        ),
    ]
