# Generated by Django 3.2.22 on 2023-11-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlab_app', '0002_alter_student_table_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_table',
            name='semester',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
