# Generated by Django 3.2.22 on 2023-11-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlab_app', '0003_student_table_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_table',
            name='dept_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam_table',
            name='details',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lab_assistant_table',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_table',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student_table',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
