# Generated by Django 3.2.22 on 2023-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlab_app', '0005_alter_staff_table_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_table',
            name='qualification',
            field=models.TextField(),
        ),
    ]
