# Generated by Django 3.2.22 on 2023-11-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlab_app', '0006_alter_staff_table_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_table',
            name='duration',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam_table',
            name='syllabus',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
