# Generated by Django 3.2.22 on 2023-11-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlab_app', '0007_auto_20231118_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_table',
            name='details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exam_table',
            name='syllabus',
            field=models.CharField(max_length=1000),
        ),
    ]
