# Generated by Django 3.2.22 on 2023-11-18 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smartlab_app', '0008_auto_20231118_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_table',
            old_name='details',
            new_name='HDD',
        ),
        migrations.AddField(
            model_name='system_table',
            name='RAM',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_table',
            name='SSD',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_table',
            name='processor',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
