# Generated by Django 3.2.22 on 2023-11-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlab_app', '0009_auto_20231118_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_table',
            name='sem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
