# Generated by Django 3.2.22 on 2023-11-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartlab_app', '0010_course_table_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrnsht', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.system_table')),
            ],
        ),
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.system_table')),
            ],
        ),
        migrations.CreateModel(
            name='command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlab_app.system_table')),
            ],
        ),
    ]
